config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :products
  resources :orders, only: [:index, :show, :create]
  get "my_sales", to: "pages#my_sales"
  get "my_products", to: "pages#my_products"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  
  validates :name, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :orders
  has_one_attached :image

  validates :name, :description, :price, :stock, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :sales, through: :products, source: :orders
  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
    @user_orders = current_user.orders
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @product = Product.find(params[:order][:product_id])
    @order.total = @product.price * @order.quantity
    if @order.save
      redirect_to order_path(@order)
    else
      render 'products/show', status: :unprocessable_entity
    end
  end

  def my_orders
    @my_orders = Order.where(user_id: current_user.id)
    #iterar array en la vista
  end

  def show
    @order = Order.find(params[:id])
  end


  private
  def order_params
    params.require(:order).permit(:quantity, :order_date, :product_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    if params[:query].present?
      @products = Product.where("name ILIKE ?", "%#{params[:query]}%")

    else
      @products = Product.limit(10)
    end
  end

  def my_sales
    @sales = current_user.sales
  end

  def my_products
    @products = current_user.products
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: [ :index ]
   def index
      @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @order = Order.new
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to my_products_path(@product)
  end

  def destroy
    @product.destroy
    redirect_to my_products_path, status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :category_id, :image)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mercado Artesanal</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@6.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

  <style>
    html, body {
      height: 100%;
    }

    .page-wrapper {
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }

    footer {
      margin-top: auto;
    }
  </style>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>

<footer class="bg-custom text-white">
  <div class="container">
    <div class="row d-flex justify-content-between align-items-start">
      <!-- Sección 1: Redes Sociales -->
      <div class="col-md-4 col-12 mb-3">
        <h5 class="mb-2 fw-bold" style="font-size: 1rem;">Socials</h5> <!-- Título más pequeño -->
        <ul class="list-unstyled social-icons">
          <li><a href="#" class="text-white"><i class="fab fa-facebook fa-0.8x"></i></a></li> <!-- Íconos más pequeños -->
          <li><a href="#" class="text-white"><i class="fab fa-instagram fa-0.8x"></i></a></li>
          <li><a href="#" class="text-white"><i class="fab fa-twitter fa-0.8x"></i></a></li>
        </ul>
      </div>

      <!-- Sección 2: Información de contacto -->
      <div class="col-md-4 col-12 mb-3">
        <h5 class="mb-2 fw-bold" style="font-size: 1rem;">Contact</h5> <!-- Título más pequeño -->
        <p style="font-size: 0.9rem;">Balderas S/N, Colonia Centro, Centro, Cuauhtémoc, 06040 Ciudad de México, CDMX</p>
        <p style="font-size: 0.9rem;">Phone number: (123) 456-7890</p>
        <p style="font-size: 0.9rem;">Email: contacto@mercadoartesanal.com</p>
      </div>

      <!-- Sección 3: Ubicación -->
      <div class="col-md-4 col-12 mb-3">
        <h5 class="mb-2 fw-bold" style="font-size: 1rem;">Ubication</h5> <!-- Título más pequeño -->
        <iframe
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3762.542472514285!2d-99.15040732478569!3d19.432164681847116!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1ff2adf95c423%3A0x2a84c0b1068a275c!2sBalderas%2C%20Colonia%20Centro%2C%20Centro%2C%20Ciudad%20de%20M%C3%A9xico%2C%20CDMX%2C%20M%C3%A9xico!5e0!3m2!1ses-419!2spe!4v1733422528232!5m2!1ses-419!2spe"
          width="100%" height="150" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
        </iframe>
      </div>
    </div>
  </div>
</footer>

  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="products-container">
  <h2 class="fw-bold text-center mb-4">My Orders</h2>
    <% if @orders.present? %>
      <% @orders.each do |order| %>
        <div class="card-product mb-4 p-3" style="position: relative;">
          <%= cl_image_tag(order.product.image.key, alt: order.product.name, class: "img-fluid mb-2") %>
          <div class="card-product-infos">
            <h2><%= order.product.name %></h2>
            <p><%= order.product.description %></p>
            <p>Quantity: <%= order.quantity %><br>Total: $<%= order.total %></p>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-warning" role="alert">
        You have no orders registered.
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div style="margin-top: 50px;">
</div>

<h2 class="text-center my-4 ticket-title">Order Details</h1>

<div class="ticket-card mx-auto">
  <div class="ticket-body">
    <h5 class="ticket-title"><strong>Product Sold:</strong> <%= @order.product.name %></h5>
    <p class="ticket-text"><strong>Product Description:</strong> <%= @order.product.description %></p>
    <p class="ticket-text"><strong>Quantity Sold:</strong> <%= @order.quantity %></p>
    <p class="ticket-text"><strong>Order Total:</strong> $<%= @order.total %></p>
  </div>
</div>

<div class="d-flex justify-content-center mt-5">
  <%= link_to 'My Orders', orders_path, class: "btn btn-primary btn-lg mb-4" %>
</div>

<div class="container mt-5">
</div>

app/views/pages/home.html.erb
<body class="bg-light">
  <div class="page-wrapper">
    <!-- Header (Texto centrado y video de fondo) -->
    <header class="hero text-black py-5 text-center" style="position: relative; height: 550px; overflow: hidden;">
      <!-- Video de fondo -->
      <video autoplay muted loop id="video-background" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; object-fit: cover; z-index: -2;">
        <source src="https://static.vecteezy.com/system/resources/previews/034/047/023/mp4/hippies-and-tribal-necklaces-hanging-in-stall-hawking-crafts-free-video.mp4" type="video/mp4">
      </video>

      <!-- Capa de superposición oscura -->
      <div class="overlay" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.3); z-index: -1;"></div>

      <!-- Contenedor de texto centrado -->
      <div class="container" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 1; color: white;">
        <h1 class="fw-bold text-shadow">Welcome to Mercado Artesanal</h1>
        <p class="text-shadow typing-effect text-big">Buy and sell products online quickly and securely.</p>
      </div>
    </header>

    <!-- Sección de Productos -->
<!-- Sección de Productos -->
<div class="container my-5" style="margin-top: 40px;">
  <h2 class="fw-bold text-center mb-4">Products</h2>

  <!-- Formulario de búsqueda (fuera del condicional de productos) -->
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: "#", method: :get, class: "d-flex justify-content-center" do |f| %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search for products..." %>
        <%= f.button "<i class='bi bi-search' style='color: #ffff;'></i>".html_safe, class: "btn btn-outline-custom" %>
      <% end %> <!-- Este es el 'end' que cierra el 'form_with' -->
    </div>
  </div>
  <!-- Fin del formulario -->
<% if @products.present? %>

  <!-- Lista de productos -->
  <div class="row justify-content-center" style="margin-top: 40px;">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6 mb-4 d-flex justify-content-center">
        <div class="card shadow-sm" style="height: 400px; width: 250px; display: flex; flex-direction: column;">
          <!-- Verificamos si el producto tiene una imagen -->
          <% if product.image.attached? %>
            <!-- Mostramos la imagen si está adjunta -->
            <%= image_tag url_for(product.image), class: 'card-img-top', alt: product.name, style: 'object-fit: cover; height: 200px;' %>
          <% else %>
            <!-- Si no tiene imagen, mostramos una imagen predeterminada -->
            <%= image_tag 'default-product-image.jpg', class: 'card-img-top', alt: 'Default Product Image', style: 'object-fit: cover; height: 200px;' %>
          <% end %>

          <div class="card-body d-flex flex-column" style="height: 100%;">
            <h5 class="card-title"><%= product.name %></h5>
            <p class="card-text">$<%= product.price %></p>

            <!-- Botón de "See more" -->
            <div class="mt-auto text-center">
              <%= link_to 'See more', product_path(product), class: 'btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% else %>
  <!-- Si no hay productos -->
  <h2 style="display: flex; justify-content: center; align-items: center; height: 300px;" class="text-center mb-4">
    Results not found
  </h2>
<% end %>
<!-- Este es el 'end' que cierra el 'if' de @products.present? -->



<div class="container my-5 py-4 bg-light shadow" style="box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2); display: flex; justify-content: center; align-items: center; height: 350px;">
  <div>
    <h2 class="fw-bold text-center mb-4">About Us</h2>
    <div class="row justify-content-center">
      <div class="col-lg-8 col-md-10">
        <p class="lead text-center">
          Welcome to Mercado Artesanal! We are an online marketplace that connects artisans and crafters with customers looking for unique, handmade products. Our goal is to provide a platform for local artisans to showcase their work and sell directly to consumers, ensuring fair prices for both buyers and sellers.
        </p>
        <p class="text-center">
          Our team is dedicated to promoting traditional craftsmanship and ensuring that every purchase made through our platform supports local artisans and their communities.
        </p>
      </div>
    </div>
  </div>
</div>


<div class="container mt-5">
  <!-- Aquí va tu siguiente contenido -->
</div>



    <!-- JavaScript necesario -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
  </div> <!-- Fin del page-wrapper -->
</body>

app/views/pages/my_products.html.erb
<div class="products-container">
  <h2 class="fw-bold text-center mb-4">My Products</h2>

  <div class="container">
    <div class="row mb-4">
      <div class="col-md-12 d-flex justify-content-center">
        <%= link_to "Add Product", new_product_path, class: 'btn btn-primary' %>
      </div>
    </div>

    <% if @products.present? %>
      <% @products.each do |product| %>
        <div class="card-product mb-4 p-3" style="position: relative;">
          <%= cl_image_tag(product.image.key, alt: product.name, class: "img-fluid mb-2") %>
          <div class="card-product-infos">
            <h2><%= product.name %></h2>
            <p><%= product.description %></p>
            <p>Price: $<%= product.price %><br>Stock: <%= product.stock %></p>
          </div>
          <div class="button-container d-flex justify-content-end" style="position: absolute; right: 10px; bottom: 10px;">
            <%= link_to "Edit", edit_product_path(product.id), class: 'btn btn-primary me-2' %>
            <%= button_to "Delete", product_path(product.id), method: :delete, data: { confirm: "Are you sure?", turbo: false }, class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-warning" role="alert">
        You have no products registered.
      </div>
    <% end %>
  </div>
</div>

app/views/pages/my_sales.html.erb
<div class="products-container">
  <h2 class="fw-bold text-center mb-4">My Sales</h2>

    <% if @sales.present? %>
      <% @sales.each do |sale| %>
        <div class="card-product mb-4 p-3" style="position: relative;">
          <%= cl_image_tag(sale.product.image.key, alt: sale.product.name, class: "img-fluid mb-2") %>
          <div class="card-product-infos">
            <h2><%= sale.product.name %></h2>
            <p>Sale Date: <%= sale.created_at.strftime("%d/%m/%Y") %></p>
            <p>Quantity: <%= sale.quantity %><br>Total: $<%= sale.total %></p>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-warning" role="alert">
        You have no sales registered.
      </div>
    <% end %>
  </div>
</div>

app/views/products/edit.html.erb
<h1 class="text-center my-4 mt-4 mb-4">Edit Product</h1>

<div class="container d-flex justify-content-center mb-5">
  <div class="card shadow-sm p-4" style="max-width: 600px; width: 100%;">
    <%= simple_form_for @product do |f| %>
      <div class="mb-3">
        <%= f.input :name, label: "Name", input_html: { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= f.input :description, label: "Description", input_html: { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= f.input :price, label: "Price", input_html: { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= f.input :stock, label: "Stock", input_html: { class: "form-control" } %>
      </div>

      <div class="mb-3">
        <%= f.input :category_id, collection: Category.all, label_method: :name, value_method: :id, prompt: "Select category", label: "Category", input_html: { class: "form-control" } %>
      </div>

      <div class="text-center">
        <%= f.button :submit, "Edit", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container text-container mt-5">
  <h2 class="text-center fw-bold">Products from Mexican Crafts</h1>
  <p class="text-center mt-4 mb-3 text-big">Explore handcrafted products showcasing Mexico's rich cultural heritage,<br>
    from vibrant textiles and ceramics to intricate wooden carvings and silver jewelry. <br>
    Each piece is a testament to traditional craftsmanship.
    </p></div>

<div class="container my-5">
  <div class="row justify-content-center">
    <% @products.each do |product| %>
      <div class="col-md-3 col-sm-6 mb-4 d-flex justify-content-center" >

        <div class="card custom-shadow custom-border rounded">
          <div class="img-container" style="height: 350px; overflow: hidden;">
            <%= cl_image_tag(product.image.key, class: "card-img-top img-fluid mx-auto d-block", alt: product.name, style: "object-fit: cover; height: 100%; width: 100%;") %>
          </div>


          <div class="card-body">
            <h5 class="card-title text-center"><%= product.name %></h5>
            <p class="card-text text-center"><%= number_to_currency(product.price) %></p>
            <p class="card-text text-center text-muted"><%= product.category.name if product.category %></p>
            <div class="d-flex justify-content-center">
              <%= link_to 'See More', product_path(product), class: 'btn btn-primary btn-sm' %>
            </div>
          </div>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div style="height: 50px;"></div>
<h1 class="text-center fw-bold">New Product</h1>
<div class="w-50 container shadow mt-5 p-5 justify-content-center">
  <ul>
    <%=simple_form_for @product do |f|%>
      <li class="fw-bold text-big"><%=f.input :name %></li>
      <li class="fw-bold text-big"><%=f.input :price%></li>
      <li class="fw-bold text-big"><%=f.input :description%></li>
      <li class="fw-bold text-big"><%=f.input :stock%></li>
      <li class="fw-bold text-big"><%=f.association :category%></li>
      <li class="fw-bold text-big"><%=f.input :image, as: :file%></li>
      <%=f.submit "Add New Product", class:"btn btn-primary w-100"%>
    </ul>
</div>
<%end%>
<div style="height: 200px;"></div>

app/views/products/show.html.erb
<div style="height: 50px;"></div>
<h2 class="text-center my-4 fw-bold">Product Information</h1>

<div class="card mx-auto mb-4" style="width: 40rem; border: 1px solid #ccc; padding: 25px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.2);">
  <div class="card-body">

    <div class="text-center mb-3">
      <%= cl_image_tag(@product.image.key, width: 200, height: 150, crop: :fill, class: "img-fluid rounded") %>
    </div>
    <h4 class="text-center mb-3"><strong><%= @product.name %></strong></h4>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <td><strong>Description:</strong></td>
          <td><%= @product.description %></td>
        </tr>
        <tr>
          <td><strong>Price:</strong></td>
          <td>$<%= @product.price %></td>
        </tr>
        <tr>
          <td><strong>Available Quantity:</strong></td>
          <td><%= @product.stock %></td>
        </tr>
      </tbody>
    </table>

    <h6 class="mb-3 mt-4"><strong>Would you like to buy?</strong></h6>
    <%= simple_form_for @order do |f| %>
      <%= f.hidden_field :sale_date, value: Date.today %>
      <%= f.hidden_field :product_id, value: @product.id %>

      <div class="mb-3">
        <%= f.input :quantity, label: "Quantity", input_html: { class: "form-control" }, label_html: { class: "form-label" } %>
      </div>

      <div class="d-flex justify-content-center">
        <%= f.submit "Buy now", class: "btn btn-primary" %>
      </div>

    <% end %>
  </div>
</div>
<div style="height: 100px;"></div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
  <div class="container d-flex flex-column align-items-center w-100">
    <!-- Logo -->
    <a class="navbar-brand mb-3" href="<%= root_path %>">
      <%= image_tag("mercado_artesanal_color.png", alt: "Mercado Artesanal Logo", class: "img-fluid img-hover-opacity", style: "max-width: 200px;") %>
    </a>

    <!-- Menú de navegación -->
    <div class="collapse navbar-collapse text-big">
      <ul class="navbar-nav d-flex justify-content-center gap-3">
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to 'Home', root_path, class: 'nav-link custom-link-color' %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(products_path) %>">
          <%= link_to 'Products', products_path, class: 'nav-link custom-link-color' %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(my_products_path) %>">
          <%= link_to 'My Products', my_products_path, class: 'nav-link custom-link-color' %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(orders_path) %>">
          <%= link_to 'My Orders', orders_path, class: 'nav-link custom-link-color' %>
        </li>
        <li class="nav-item <%= 'active' if current_page?(my_sales_path) %>">
          <%= link_to 'My Sales', my_sales_path, class: 'nav-link custom-link-color' %>
        </li>
        <li class="nav-item <%= 'active' if current_page?('/users/sign_in') %>">
<%= link_to 'Sign In', new_user_session_path, class: 'nav-link custom-link-color' if !user_signed_in?%>
  <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link custom-link-color' if user_signed_in?%>
  </li>
      </ul>
    </div>
  </div>
</nav>